export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

export const GET_ORDER_LIST = "GET_ORDER_LIST";

export const GET_ORDER = "GET_ORDER";
export const ADD_ORDER = "ADD_ORDER";

export const GET_ITEMS = "GET_ITEMS";

export const ADD_ITEMS_TO_ORDER = "ADD_ITEMS_TO_ORDER";
export const DELETE_ITEM_FROM_ORDER = "DELETE_ITEM_FROM_ORDER";
export const UPDATE_ITEM_COUNT_FROM_ORDER = "UPDATE_ITEM_COUNT_FROM_ORDER";

export const ITEMS_LOADING = "ITEMS_LOADING";
